CREATE TABLE sipkan.tb_unit (
	id INT NULL,
	nama_unit varchar(100) NULL,
	entitas varchar(10) NULL,
	nama_pemilik varchar(100) NULL,
	penanggungjawab varchar(100) NULL,
	modalusaha varchar(100) NULL,
	omzettahunanupi DOUBLE NULL,
	tahun_berdiri varchar(4) NULL,
	id_kelompok INT NULL,
	kontakperson varchar(15) NULL,
	provinsi varchar(20) NULL,
	kabupaten varchar(20) NULL,
	kecamatan varchar(20) NULL,
	kelurahan varchar(20) NULL,
	alamat varchar(100) NULL,
	kodepost varchar(10) NULL,
	nib varchar(50) NULL,
	kbli varchar(100) NULL,
	npwp varchar(50) NULL,
	no_iup varchar(100) NULL,
	no_skp varchar(100) NULL,
	no_haccp varchar(100) NULL,
	no_siup varchar(100) NULL,
	no_akte varchar(100) NULL,
	email varchar(100) NULL,
	nama_produk varchar(100) NULL,
	teknologi_produksi varchar(100) NULL,
	tujuan_pemasaran_domestik varchar(100) NULL,
	tujuan_pemasaran_mancanegara varchar(100) NULL,
	realisasi_pertahun varchar(100) NULL,
	asal_wilayah varchar(100) NULL,
	jenis_ikan INT NULL,
	bentuk_ikan varchar(100) NULL,
	kebutuhan_perhari varchar(100) NULL,
	sni varchar(100) NULL,
	jumlah_unit varchar(100) NULL,
	jumlah_kapasitas varchar(100) NULL,
	tenagakerjaasing_laki INT NULL,
	tenagakerjaasing_perempuan varchar(100) NULL,
	tenagakerjatetap_laki varchar(100) NULL,
	tenagakerjatetap_perempuan varchar(100) NULL,
	jumlahharikerja_perbulan varchar(100) NULL,
	jumlahshift_perhari varchar(100) NULL,
	upi varchar(100) NULL,
	produksi varchar(100) NULL,
	mutu varchar(100) NULL,
	sumber varchar(100) NULL,
	pengolahan varchar(100) NULL,
	volume varchar(100) NULL,
	produksi_sendiri varchar(100) NULL,
	pembelian_dari varchar(100) NULL,
	bentuk_es varchar(100) NULL,
	penggunaan_es varchar(100) NULL,
	bahan_tambahan_pangan varchar(100) NULL,
	bahan_kimia_yangdigunakan varchar(100) NULL,
	bahan_lainnya varchar(100) NULL,
	jenis_bahan_kemasan varchar(100) NULL,
	informasi_lainnya varchar(100) NULL,
	catatan varchar(100) NULL,
	CONSTRAINT tb_unit_PK PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;
